export { default as Hero } from "./Hero"
export { default as About } from "./About"
export { default as Experience } from "./Experience"
export { default as Articles } from "./Articles"
export { default as Comics } from "./Comics"
export { default as Projects } from "./Projects"
export { default as Contact } from "./Contact"
